// Add local photos or videos to any media array. See README.md for examples.
window.portfolio = {
  projects: [
    { id:'linkage', title:'Motorized linkage', category:'Mechanical design', date:'Dec 2025 — May 2026', description:'From linkage geometry to closed-loop control. A motorized mechanism designed to detect and illuminate moving targets.', tags:['CAD & simulation','PID control','Machining'], details:['Designed the mechanism using CAD and multibody simulation to achieve at least 60° angular displacement, less than 30° transmission-angle deviation, and a 1.5-second displacement time.','Optimized dynamics through inertia matching, balancing transmission performance against a mechanical-efficiency target above 80% and a total system weight at or below 10 lb.','Manufactured and assembled components using mill and lathe machining, 3D printing, and waterjet cutting. Integrated a motor, limit switch, photosensor, and Arduino circuitry.','Developed and tuned PID motion control through testing; analyzed hard-stop loading and link stresses above 240 MPa.'], media:[{type:'video', src:'media/Motor_Linkage_Demo.mp4', caption:'Motorized linkage demonstration.'}] },
    { id:'robot', title:'Robotic mobility platform', category:'Robotics', date:'Jan — Apr 2025', description:'A compact, competition-ready robot built to retrieve, navigate, and interact. Placed in the top 10% of the robotics competition.', tags:['SolidWorks','Fabrication','Top 10% finish'], details:['Designed a robotic mobility platform within a 10 × 10 × 12-inch envelope, including rack-and-pinion and magnetic extension mechanisms for object retrieval and placement.','Led fabrication using manual mill and lathe machining, waterjet cutting, and 3D printing. Created engineering drawings in SolidWorks and worked through tolerance stackup and error propagation.','Operated the platform in a competition to collect a flag, engage buttons and switches, and deposit the flag, placing in the top 10%.'], media:[{type:'video', src:'media/RMP_Demo.mp4', caption:'Robotic mobility platform demonstration.'}] },
    { id:'solar', title:'Michigan Solar Car', category:'Mechanical design', date:'Aug 2023 — May 2024', description:'Steering-system development and structural design for a solar-powered race car competing on the world stage.', tags:['Siemens NX','FEA','Vehicle dynamics'], details:['Researched and co-designed a trochoidal steering system for the 3,000 km 2023 Bridgestone World Solar Challenge, contributing to the team’s fourth-place global finish.','Engineered a ballast box to meet American Solar Challenge regulations, refining structural integrity, safety, comfort, and performance.','Used Siemens NX for CAD, Altair Adams for dynamic simulation, and HyperWorks for finite element analysis to validate and refine steering arms.'], cover:'media/SolarCar_Angle1.jpeg', media:[{type:'image', src:'media/SolarCar_Angle1.jpeg', alt:'Close-up of the solar car cockpit and steering assembly', caption:'Steering assembly inside the Michigan Solar Car.'}, {type:'image', src:'media/Me_in_solarcar.jpeg', alt:'Victor seated in the solar car cockpit wearing safety glasses', caption:'Inside the Michigan Solar Car cockpit.'}] },
    { id:'hovercraft', title:'Laser-cut hovercraft', category:'Robotics', date:'Dec 2023 — May 2024', description:'An exploration of lift, stability, and lightweight design—taking a hovercraft from aerodynamic simulation to a working prototype.', tags:['CATIA','STAR-CCM+','Arduino'], details:['Designed a lightweight hovercraft using CATIA and STAR-CCM+ aerodynamic simulations to refine lift and stability, with Arduino-based controls.','Built a 3D-printed impeller and laser-cut frame, translating digital models into a functional prototype and developing G-code manufacturing experience.','Authored a comprehensive engineering report and presented a formal design review to faculty and peers.'], media:[] }
  ],
  experiences:[
    {title:'Wind turbine research intern',company:'RWTH Aachen University · Aachen, Germany',date:'May — Jul 2026',description:'Investigating how operating parameters influence energy-induced failure modes in wind turbine roller bearings.',details:['Established research objectives, response variables, parameters, and experimental methods using Design of Experiments.','Simulated bearing dynamics in Simulink with parameters generated through Latin Hypercube Sampling.','Wrote MATLAB and C++ scripts to process simulation data and visualize results, including Partial Rank Correlation Coefficient heatmaps.','Presented findings in a research report and a poster at the UROP symposium.'],media:[{type:'image', src:'media/UROP_Research_Symposium.JPG', alt:'Group beside the wind turbine roller bearing research poster at the UROP symposium', caption:'Sharing wind turbine bearing research at the UROP symposium, RWTH Aachen University.'}]},
    {title:'Solar car engineering',company:'University of Michigan Solar Car Team',date:'Aug 2023 — May 2024',description:'Contributing to steering, structural design, and simulation in a multidisciplinary student engineering team.',details:['Developed steering-system concepts and refined steering arms using CAD, dynamic simulation, and FEA.','Designed a ballast box with competition compliance, structural integrity, and driver comfort in mind.'],media:[{type:'image', src:'media/Me_in_solarcar.jpeg', alt:'Victor seated in the Michigan Solar Car cockpit', caption:'Hands-on engineering with the Michigan Solar Car Team.'}]},
    {title:'Thermodynamics in Paris',company:'University of New Haven · Paris, France',date:'May — Jul 2025',description:'Studying energy systems through coursework, nuclear-energy research, and an international engineering perspective.',details:['Completed thermodynamics lectures, assignments, exams, and projects with Dr. Frederick De Meyer.','Researched nuclear fission power plants and Generation IV reactors.','Explored engineering history through museums and architectural sites, including Le Musée des Arts et Métiers.'],media:[]}
  ]
};
